[workspace]
resolver = "3"
members = [
    "crates/bit_sr_core",
    "crates/bit_sr_platform_windows",
    "crates/bit_sr_speech",
    "crates/bit_sr_engine",
    "crates/bit_sr_plugin",
    "crates/bit_sr_ui",
    "crates/bit_sr_web",
    "crates/bit_sr_platform_android",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
